apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: "managed-nfs-storagea"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi